name: sakinah
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  google_sign_in: ^6.2.2
  cloud_firestore: ^6.0.1
  firebase_storage: ^13.0.1

  google_fonts: ^6.2.1
  flutter_svg: ^2.0.7
  image_picker: ^1.0.4
  clipboard: ^2.0.2
  connectivity_plus: ^7.0.0
  hugeicons: ^1.1.1
  url_launcher: ^6.2.5
  flutter_pdfview: ^1.3.2
  path_provider: ^2.1.2
  dio: ^5.4.1
  just_audio: ^0.9.36
  audio_session: ^0.1.18
  audio_waveforms: ^1.0.5
  permission_handler: ^11.3.0
  google_generative_ai: ^0.4.7
  fl_chart: ^0.69.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    # - assets/